inputs:
  dem: ./input/BX20.tif
  gpkg: ./input/mount-hutt.gpkg
  qgz: ./input/mount-hutt.qgz
layers:
  forest: forest
  road_areas: road-areas
  roads: roads
  ski_runs: ski-runs
  lifts: lifts
model:
  include_snow: false
output:
  directory: ./output
  stem: mount_hutt
